"""empty message

Revision ID: 543fbc7142d8
Revises: 04b01b8ede3e
Create Date: 2023-08-30 14:54:28.192653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543fbc7142d8'
down_revision = '04b01b8ede3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###
